version: '3.8'

services:
  web:
    container_name: web
    restart: always
    build: .
    volumes: 
      - ./db/:/app/db
    environment: 
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      API_BASE_URL: http://localhost:3000/api/
      POST_TEXT_MAX_LENGTH: 500
    ports: 
      - 3000:3000