version: '3.8'

services:
  web:
    container_name: web
    restart: always
    build: .
    environment: 
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    volumes: 
      - ./db/:/app/db
    ports: 
      - 3000:3000